# -*- coding: utf-8 -*-
"""多语言支持：简体中文 / English / 繁體中文"""
LANGS = {'zh': '简体中文', 'en': 'English', 'zh_tw': '繁體中文'}
_current = 'zh'

def set_lang(code):
    global _current
    _current = code if code in LANGS else 'zh'

def get_lang():
    return _current

EN = {
    "插件加载失败 [%s]: %s": "Plugin load failed [%s]: %s",
    "插件 token 出错 [%s]: %s": "Plugin token error [%s]: %s",
    "插件管理": "Plugin Manager",
    "打开插件文件夹": "Open Plugins Folder",
    "添加插件(.zip/.py)": "Add Plugin (.zip/.py)",
    "刷新": "Refresh",
    "插件 = plugins 里的一个文件夹，内含 plugin.py": "A plugin is a folder inside plugins/ containing plugin.py",
    "插件名": "Plugin",
    "状态": "Status",
    "错误信息": "Error",
    "关闭": "Close",
    "已加载": "Loaded",
    "加载失败": "Failed",
    "（无插件）": "(no plugins)",
    "无法打开": "Cannot Open",
    "选择插件（.zip 或 .py）": "Select plugin (.zip or .py)",
    "插件": "Plugin",
    "所有文件": "All files",
    "添加失败": "Add Failed",
    "压缩包里找不到 plugin.py": "No plugin.py found in the archive",
    "提示": "Notice",
    "插件已存在：": "Plugin already exists: ",
    "添加插件失败": "Add Plugin Failed",
    "插件商店": "Plugin Store",
    "从插件商店下载并安装插件（安装到 plugins/ 目录，重启或刷新后生效）": "Download and install plugins from the store (installed into plugins/; takes effect after restart or refresh)",
    "正在加载插件列表…": "Loading plugin list...",
    "未配置插件商店地址（config.json 的 plugin_store_url）": "Plugin store URL not configured (plugin_store_url in config.json)",
    "加载失败：": "Load failed: ",
    "商店里暂无插件": "No plugins in the store yet",
    "共 %d 个插件": "%d plugin(s)",
    "安装": "Install",
    "已安装": "Installed",
    "已安装 · 最新": "Installed - Latest",
    "已安装 v%s · 最新": "Installed v%s - Latest",
    "已安装 v%s → v%s": "Installed v%s → v%s",
    "打开仓库": "Open Repo",
    "正在下载并安装…": "Downloading and installing...",
    "安装失败：": "Install failed: ",
    "安装完成，已刷新插件列表": "Installed; plugin list refreshed",
    "压缩包里没有 plugin.py": "No plugin.py found in the archive",
    "更新于 ": "Updated: ",
    "检测到 v%s 有新的更新（发布内容已变化）\n%s\n\n是否立即下载更新？": "Detected a new update for v%s (published content changed)\n%s\n\nDownload and update now?",
    "非法路径: %s": "Illegal path: %s",
    "仅支持 HTTPS 插件商店地址（plugin_store_url 必须使用 https://）": "Only HTTPS plugin-store URLs are supported (plugin_store_url must use https://)",
    "仅支持 HTTPS 下载地址（install_url 必须使用 https://）": "Only HTTPS download URLs are supported (install_url must use https://)",
    "下载文件校验失败（checksum 不匹配）": "Download verification failed (checksum mismatch)",
    "该插件未提供校验和，来源可信度未知，仍要安装吗？": "This plugin has no checksum in the catalog; its source is unverified. Install anyway?",
    "安装中…": "Installing...",
    "已安装 v%s · 加载失败": "Installed v%s - Failed to Load",
    "已安装 · 加载失败": "Installed - Failed to Load",
    "已安装 v%s（加载失败）→ v%s": "Installed v%s (failed) → v%s",
    "重装": "Reinstall",
    "解压文件过大（超过 %d MB 限制）": "Archive too large (over %d MB limit)",
    "压缩包内文件过多": "Too many files in archive",
    "选择照片文件夹": "Select Photo Folder",
    "未选择文件夹": "No folder selected",
    "选择输出文件夹": "Select Output Folder",
    "打开输出文件夹": "Open Output Folder",
    "0 张": "0 photos",
    "全选": "Select All",
    "全不选": "Deselect All",
    "导出水印照片": "Export Watermarked Photos",
    "取消": "Cancel",
    "就绪": "Ready",
    "水印文字": "Text",
    "模板预设": "Template Preset",
    "保存为自定义模板": "Save as Custom Template",
    "保存后可在预设里选“自定义（可保存）”恢复": "After saving, select Custom (saved) in the presets to restore",
    "模板（可编辑，换行=多行）": "Template (editable; newline = multiple lines)",
    "可用变量：{make} {model} {camera} {shutter} {aperture} {iso} {focal} {lens} {date} {time}": "Variables: {make} {model} {camera} {shutter} {aperture} {iso} {focal} {lens} {date} {time}",
    "   插件变量: ": "   Plugin variables: ",
    "相机名覆盖（留空=自动识别品牌型号）": "Camera name override (leave empty for auto-detect)",
    "样式": "Style",
    "字体": "Font",
    "添加字体文件": "Add Font File",
    "打开字体文件夹": "Open Fonts Folder",
    "把自己的 .ttf/.otf 字体放进去即可": "Put your .ttf/.otf fonts here",
    "加粗": "Bold",
    "字号(%宽)": "Font size (% width)",
    "行距": "Line spacing",
    "文字颜色": "Text color",
    "选择颜色": "Choose Color",
    "透明度": "Opacity",
    "位置": "Position",
    "横向偏移%": "H offset %",
    "纵向偏移%": "V offset %",
    "边距%": "Margin %",
    "背景/描边": "Background/Outline",
    "半透明背景条": "Semi-transparent background bar",
    "背景颜色": "Background color",
    "选择": "Choose",
    "不透明度": "Opacity",
    "内边距(×字号)": "Padding (x font size)",
    "文字描边": "Text outline",
    "描边颜色": "Outline color",
    "粗细": "Thickness",
    "文字阴影": "Text shadow",
    "阴影强度": "Shadow strength",
    "导出": "Export",
    "输出格式": "Output format",
    "JPG质量": "JPG quality",
    "导出 JPG 时保留 EXIF 信息": "Preserve EXIF when exporting JPG",
    "文件名后缀": "Filename suffix",
    "覆盖已存在的输出文件（否则自动加 (1)(2)）": "Overwrite existing files (otherwise auto-number (1) (2))",
    "插件已加载: %s": "Plugins loaded: %s",
    "检查更新": "Check for Updates",
    "当前版本 v": "Version v",
    "作者：Shiraijikuu　·　AI 协助：OpenAI Codex　·　MIT 开源": "Author: Shiraijikuu  |  AI assistance: OpenAI Codex  |  MIT License",
    "语言": "Language",
    "JPG（可保留EXIF）": "JPG (EXIF preserved)",
    "模板不能为空": "Template cannot be empty",
    "选择字体文件": "Select font file",
    "字体文件": "Font files",
    "添加字体失败": "Add Font Failed",
    "更新": "Update",
    "源码模式：请用新版本文件替换 app.py / photo.py": "Source mode: replace app.py / photo.py with the new version",
    "找不到当前程序文件：": "Cannot find the program file: ",
    "更新失败": "Update Failed",
    "选择包含相机照片的文件夹": "Select folder containing camera photos",
    "RAW 内嵌预览": "RAW embedded preview",
    "RAW 内没有可用的内嵌预览": "No usable embedded preview in this RAW",
    "选择水印输出文件夹": "Select watermark output folder",
    "没有可导出的照片（请先选择文件夹并等待扫描完成）": "No photos to export (select a folder and wait for the scan to finish)",
    "请先选择输出文件夹": "Please select an output folder first",
    "导出失败 %s: %s": "Export failed %s: %s",
    "检查更新失败": "Update check failed",
    "当前已是最新版本 v": "You already have the latest version v",
    "发现新版本": "New Version Found",
    "发现新版本 v%s\\n%s\\n\\n是否立即下载更新？": "发现新版本 v%s\\n%s\\n\\n是否立即下载更新？",
    "下载更新失败": "Update download failed",
    "更新下载完成": "Update Downloaded",
    "新版本 v%s 已下载，是否现在重启完成更新？": "New version v%s downloaded. Restart now to finish updating?",
    "导出出错": "Export Error",
    "导出完成": "Export Complete",
    "水印照片已导出到：\\n": "水印照片已导出到：\\n",
    "自定义: ": "Custom: ",
    "语言": "Language",
}

ZH_TW = {
    "插件加载失败 [%s]: %s": "插件加載失敗 [%s]: %s",
    "插件 token 出错 [%s]: %s": "插件 token 出錯 [%s]: %s",
    "插件管理": "插件管理",
    "打开插件文件夹": "打開插件文件夾",
    "添加插件(.zip/.py)": "添加插件(.zip/.py)",
    "刷新": "刷新",
    "插件 = plugins 里的一个文件夹，内含 plugin.py": "插件 = plugins 裏的一個文件夾，內含 plugin.py",
    "插件名": "插件名",
    "状态": "狀態",
    "错误信息": "錯誤信息",
    "关闭": "關閉",
    "已加载": "已加載",
    "加载失败": "加載失敗",
    "（无插件）": "（無插件）",
    "无法打开": "無法打開",
    "选择插件（.zip 或 .py）": "選擇插件（.zip 或 .py）",
    "插件": "插件",
    "所有文件": "所有文件",
    "添加失败": "添加失敗",
    "压缩包里找不到 plugin.py": "壓縮包裏找不到 plugin.py",
    "提示": "提示",
    "插件已存在：": "插件已存在：",
    "添加插件失败": "添加插件失敗",
    "插件商店": "插件商店",
    "从插件商店下载并安装插件（安装到 plugins/ 目录，重启或刷新后生效）": "從插件商店下載並安裝插件（安裝到 plugins/ 目錄，重啟或刷新後生效）",
    "正在加载插件列表…": "正在加載插件列表…",
    "未配置插件商店地址（config.json 的 plugin_store_url）": "未配置插件商店地址（config.json 的 plugin_store_url）",
    "加载失败：": "加載失敗：",
    "商店里暂无插件": "商店裡暫無插件",
    "共 %d 个插件": "共 %d 個插件",
    "安装": "安裝",
    "已安装": "已安裝",
    "已安装 · 最新": "已安裝 · 最新",
    "已安装 v%s · 最新": "已安裝 v%s · 最新",
    "已安装 v%s → v%s": "已安裝 v%s → v%s",
    "打开仓库": "打開倉庫",
    "正在下载并安装…": "正在下載並安裝…",
    "安装失败：": "安裝失敗：",
    "安装完成，已刷新插件列表": "安裝完成，已刷新插件列表",
    "压缩包里没有 plugin.py": "壓縮包裏沒有 plugin.py",
    "更新于 ": "更新於 ",
    "检测到 v%s 有新的更新（发布内容已变化）\n%s\n\n是否立即下载更新？": "檢測到 v%s 有新的更新（發布內容已變化）\n%s\n\n是否立即下載更新？",
    "非法路径: %s": "非法路徑: %s",
    "仅支持 HTTPS 插件商店地址（plugin_store_url 必须使用 https://）": "僅支持 HTTPS 插件商店地址（plugin_store_url 必須使用 https://）",
    "仅支持 HTTPS 下载地址（install_url 必须使用 https://）": "僅支持 HTTPS 下載地址（install_url 必須使用 https://）",
    "下载文件校验失败（checksum 不匹配）": "下載文件校驗失敗（checksum 不匹配）",
    "该插件未提供校验和，来源可信度未知，仍要安装吗？": "該插件未提供校驗和，來源可信度未知，仍要安裝嗎？",
    "安装中…": "安裝中…",
    "已安装 v%s · 加载失败": "已安裝 v%s · 加載失敗",
    "已安装 · 加载失败": "已安裝 · 加載失敗",
    "已安装 v%s（加载失败）→ v%s": "已安裝 v%s（加載失敗）→ v%s",
    "重装": "重裝",
    "解压文件过大（超过 %d MB 限制）": "解壓文件過大（超過 %d MB 限制）",
    "压缩包内文件过多": "壓縮包內文件過多",
    "选择照片文件夹": "選擇照片文件夾",
    "未选择文件夹": "未選擇文件夾",
    "选择输出文件夹": "選擇輸出文件夾",
    "打开输出文件夹": "打開輸出文件夾",
    "0 张": "0 張",
    "全选": "全選",
    "全不选": "全不選",
    "导出水印照片": "導出水印照片",
    "取消": "取消",
    "就绪": "就緒",
    "水印文字": "水印文字",
    "模板预设": "模板預設",
    "保存为自定义模板": "保存爲自定義模板",
    "保存后可在预设里选“自定义（可保存）”恢复": "保存後可在預設裏選“自定義（可保存）”恢復",
    "模板（可编辑，换行=多行）": "模板（可編輯，換行=多行）",
    "可用变量：{make} {model} {camera} {shutter} {aperture} {iso} {focal} {lens} {date} {time}": "可用變量：{make} {model} {camera} {shutter} {aperture} {iso} {focal} {lens} {date} {time}",
    "   插件变量: ": "   插件變量: ",
    "相机名覆盖（留空=自动识别品牌型号）": "相機名覆蓋（留空=自動識別品牌型號）",
    "样式": "樣式",
    "字体": "字體",
    "添加字体文件": "添加字體文件",
    "打开字体文件夹": "打開字體文件夾",
    "把自己的 .ttf/.otf 字体放进去即可": "把自己的 .ttf/.otf 字體放進去即可",
    "加粗": "加粗",
    "字号(%宽)": "字號(%寬)",
    "行距": "行距",
    "文字颜色": "文字顏色",
    "选择颜色": "選擇顏色",
    "透明度": "透明度",
    "位置": "位置",
    "横向偏移%": "橫向偏移%",
    "纵向偏移%": "縱向偏移%",
    "边距%": "邊距%",
    "背景/描边": "背景/描邊",
    "半透明背景条": "半透明背景條",
    "背景颜色": "背景顏色",
    "选择": "選擇",
    "不透明度": "不透明度",
    "内边距(×字号)": "內邊距(×字號)",
    "文字描边": "文字描邊",
    "描边颜色": "描邊顏色",
    "粗细": "粗細",
    "文字阴影": "文字陰影",
    "阴影强度": "陰影強度",
    "导出": "導出",
    "输出格式": "輸出格式",
    "JPG质量": "JPG質量",
    "导出 JPG 时保留 EXIF 信息": "導出 JPG 時保留 EXIF 信息",
    "文件名后缀": "文件名後綴",
    "覆盖已存在的输出文件（否则自动加 (1)(2)）": "覆蓋已存在的輸出文件（否則自動加 (1)(2)）",
    "插件已加载: %s": "插件已加載: %s",
    "检查更新": "檢查更新",
    "当前版本 v": "當前版本 v",
    "作者：Shiraijikuu　·　AI 协助：OpenAI Codex　·　MIT 开源": "作者：Shiraijikuu　·　AI 協助：OpenAI Codex　·　MIT 開源",
    "语言": "語言",
    "JPG（可保留EXIF）": "JPG（可保留EXIF）",
    "模板不能为空": "模板不能爲空",
    "选择字体文件": "選擇字體文件",
    "字体文件": "字體文件",
    "添加字体失败": "添加字體失敗",
    "更新": "更新",
    "源码模式：请用新版本文件替换 app.py / photo.py": "源碼模式：請用新版本文件替換 app.py / photo.py",
    "找不到当前程序文件：": "找不到當前程序文件：",
    "更新失败": "更新失敗",
    "选择包含相机照片的文件夹": "選擇包含相機照片的文件夾",
    "RAW 内嵌预览": "RAW 內嵌預覽",
    "RAW 内没有可用的内嵌预览": "RAW 內沒有可用的內嵌預覽",
    "选择水印输出文件夹": "選擇水印輸出文件夾",
    "没有可导出的照片（请先选择文件夹并等待扫描完成）": "沒有可導出的照片（請先選擇文件夾並等待掃描完成）",
    "请先选择输出文件夹": "請先選擇輸出文件夾",
    "导出失败 %s: %s": "導出失敗 %s: %s",
    "检查更新失败": "檢查更新失敗",
    "当前已是最新版本 v": "當前已是最新版本 v",
    "发现新版本": "發現新版本",
    "发现新版本 v%s\\n%s\\n\\n是否立即下载更新？": "發現新版本 v%s\\n%s\\n\\n是否立即下載更新？",
    "下载更新失败": "下載更新失敗",
    "更新下载完成": "更新下載完成",
    "新版本 v%s 已下载，是否现在重启完成更新？": "新版本 v%s 已下載，是否現在重啓完成更新？",
    "导出出错": "導出出錯",
    "导出完成": "導出完成",
    "水印照片已导出到：\\n": "水印照片已導出到：\\n",
    "自定义: ": "自定義: ",
    "语言": "語言",
}

def tr(text):
    if _current == 'zh':
        return text
    d = EN if _current == 'en' else ZH_TW
    return d.get(text, text)
